[tool.bumpversion]
current_version = "0.1.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
tag = true
sign_tags = true
tag_name = "sent-emoclass-kb-emoclass-v{new_version}"
tag_message = "version(sent-emoclass-kb-emoclass) {new_version}"
allow_dirty = false
commit = true
message = "chore(release): Bump version: {current_version} â†’ {new_version}"
commit_args = "--no-verify"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "src/sbx_sentence_emotional_classification_kb_emoclass/metadata.yaml"
search = "updated: \\d{{4}}-\\d{{2}}-\\d{{2}}"
replace = "updated: {now:%Y-%m-%d}"
regex = true

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = '## [unreleased]'
replace = '## [{new_version}] - {now:%Y-%m-%d}'

[[tool.bumpversion.files]]
filename = "src/sbx_sentence_emotional_classification_kb_emoclass/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'
